[package]
name = "get-all-crates"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
description = "Download .crate files of all version of all crates from crates.io"
edition = "2021"
license = "MIT"
repository = "https://github.com/dtolnay/get-all-crates"

[dependencies]
anyhow = "1"
clap = { version = "3.1", default-features = false, features = ["std", "derive", "cargo", "color"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.69"
tracing = "0.1.29"
tracing-subscriber = { version = "0.2.18", features = ["env-filter", "registry"] }
tokio = { version = "1.21", features = ["full"] }
reqwest = { version = "0.11", default-features = false, features = ["json", "stream", "rustls-tls", "cookies", "multipart", "gzip", "brotli", "deflate", "trust-dns"] }
futures = "0.3.7"
walkdir = "2.3"
num_cpus = "1.3"
pretty_toa = "1"
regex = "1.6"
url = "2"
